import {build} from 'esbuild';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url));
const read=name=>readFile(path.join(root,name),'utf8');
const escape=value=>value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const license=await read('LICENSE'),fontLicense=await read('public/fonts/baloo2-OFL.txt');
const notices=[license,'Baloo 2 (unmodified variable font)',fontLicense,'esbuild 0.28.2 (build tool)',await read('licenses/esbuild-MIT.txt')].join('\n\n');
await writeFile(path.join(root,'public/LICENSE.txt'),license);
await writeFile(path.join(root,'public/THIRD_PARTY_NOTICES.txt'),notices);
await writeFile(path.join(root,'public/credits.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Remember Your Numbers credits</title><style>body{max-width:800px;margin:40px auto;padding:20px;font-family:system-ui;line-height:1.6}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style><h1>Credits and licenses</h1><p><a href="./">Back to the game</a></p><p>Original game by Jess Maddox with AI coding assistance. Demo learners and numbers are wholly fictional.</p><pre>${escape(notices)}</pre></html>`);
await mkdir(path.join(root,'public/dist'),{recursive:true});await mkdir(path.join(root,'artifacts'),{recursive:true});
const result=await build({entryPoints:[path.join(root,'public/app.js')],bundle:true,format:'iife',target:['es2022'],write:false,legalComments:'inline'});
const script=result.outputFiles[0].text;
await writeFile(path.join(root,'public/dist/app.js'),script);
const font=await readFile(path.join(root,'public/fonts/Baloo2-Variable.ttf'));
const css=(await read('public/style.css')).replace('./fonts/Baloo2-Variable.ttf',()=>`data:font/ttf;base64,${font.toString('base64')}`);
let html=await read('public/index.html');
html=html.replace('<link rel="stylesheet" href="./style.css">',()=>`<style>${css}</style>`);
html=html.replace('<script src="./dist/app.js" defer></script>',()=>`<script>${script.replaceAll('</script','<\\/script')}</script>`);
html=html.replace('<a href="./credits.html">Credits and licenses</a>',()=>'<button onclick="document.getElementById(\'credits\').showModal()">Credits and licenses</button>');
html=html.replace('</body>',()=>`<dialog id="credits"><button onclick="document.getElementById('credits').close()">Close credits</button><h2>Credits and licenses</h2><pre>${escape(notices)}</pre></dialog>\n</body>`);
await writeFile(path.join(root,'artifacts/Remember-Your-Numbers.html'),html);
console.log('Built the full hosted app and artifacts/Remember-Your-Numbers.html.');
